version: '3'

services:
  pay:
    container_name: pay
    image: registry.cn-hangzhou.aliyuncs.com/ggball/pay:latest
    ports:
      - "9002:9002"
    environment:
      - JAVA_OPTS=-Xmx512m
    volumes:
      - ./data:/app/data
    env_file:
      - .env

 